-- DeleteExisting words if any
DELETE FROM "Word";

-- Insert all 47 words
INSERT INTO "Word" (id, lemma, definition, "partOfSpeech", "isActive", "createdAt")
VALUES 
  (gen_random_uuid(), 'ABBACARE', 'Vagare con la mente, fantasticare', 'verbo', true, NOW()),
  (gen_random_uuid(), 'ABBAMBINARE', 'Trasportare oggetti pesanti alternando il peso sugli spigoli', 'verbo', true, NOW()),
  (gen_random_uuid(), 'ABBALLARE', 'Fare balle di paglia o fieno legandole per la conservazione', 'verbo', true, NOW()),
  (gen_random_uuid(), 'ABBURATTARE', 'Setacciare la farina per separarla dalla crusca', 'verbo', true, NOW()),
  (gen_random_uuid(), 'ALETTE', 'Lembi ripiegati all''interno della sopracopertina di un libro', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'ARCOSOLIO', 'Nicchia sepolcrale ad arco', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'BROSCIA', 'Brodaglia annacquata e insipida', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'BROLO', 'Terreno coltivato recintato, posto intorno a una casa', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'BRULOTTO', 'Imbarcazione imbottita di esplosivo e diretta verso navi nemiche', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'BRUZZAGLIA', 'Accozzaglia di gente da poco, marmaglia', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'BURBANZA', 'Boria, alterigia vanitosa e sprezzante', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'CABOTAGGIO', 'Navigazione marittima costiera con piccole navi', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'CACHINNO', 'Risata irrefrenabile e sguaiata', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'CARACCA', 'Grande veliero mercantile e da guerra', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'CARAMOGIO', 'Nano di corte deforme e grottesco', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'CHIETINERIA', 'Devozione falsa, ostentata e ipocrita', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'CODRIONE', 'Parte del dorso degli uccelli in cui si impianta la coda', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'GABBANUCCIO', 'Corto mantello da lavoro rustico e povero', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'GAGLIOTTO', 'Sciocco presuntuoso che ostenta sapere che non possiede', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'GIACCHIO', 'Rete da pesca circolare lanciata a mano', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'GINNETTO', 'Cavallo di razza spagnola, agile e snello', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'GUADINO', 'Retino conico e dal lungo manico per il recupero del pesce all''amo', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'KORE', 'Scultura arcaica che rappresenta la grazia femminile', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'LABBREGGIARE', 'Parlare mormorando sottovoce', 'verbo', true, NOW()),
  (gen_random_uuid(), 'MAGANZÉSE', 'Traditore, fellone', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'MATE', 'Arbusto sudamericano, le cui foglie si usano per infusi', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'MELANGOLA', 'Arancio amaro dalla scorza aromatica', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'MOLAZZA', 'Macchinario per triturare e macinare', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'MATRACCIO', 'Recipiente di vetro da laboratorio, di forma sferica e collo lungo', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'NAU', 'Veliero portoghese per rotte commerciali di lunga percorrenza', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'NIQUITOSO', 'Malvagio, pieno di malizia e vizi', 'aggettivo', true, NOW()),
  (gen_random_uuid(), 'PABOLO', 'Foraggio per animali domestici', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'PECORAGGINE', 'Comportamento servile per viltà o mancanza di intelligenza', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'PEPLO', 'Indumento femminile a drappo lasciato cadere in pieghe dalle spalle', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'PELTA', 'Nell''antica Grecia, piccolo scudo a mezzaluna', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'PIATTONATA', 'Colpo dato con la parte piatta della lama di una spada', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'PITTIMA', 'Persona fastidiosa pagata per seguire i debitori', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'POLEOGRAFIA', 'Disciplina che studia la genesi e lo sviluppo delle città', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'RISGUARDI', 'Prima e ultima pagina incollate alla copertina di un libro', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'SALACCAIO', 'Venditore ambulante di pesce conservato sotto sale', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'SALAPUZIO', 'Uomo di piccola statura, saccente e presuntuoso', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'SERTO', 'Corona circolare intrecciata, ghirlanda', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'SIROCCHIA', 'Sorella', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'SOLATIO', 'Luogo soleggiato, esposto a mezzogiorno', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'UROPIGIO', 'Ghiandola sebacea posta nella coda degli uccelli', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'VARROCCHIO', 'Argano medievale per sollevare pesi notevoli', 'sostantivo', true, NOW()),
  (gen_random_uuid(), 'ZINZINAIRE', 'Bere a piccoli sorsi', 'verbo', true, NOW());
